### ISSUE TITLE
Failed to execute 'fetch' on Window

### ISSUE THREAD

**Issue by javiermrz** [hqoss/node-http-client#15]
Hi,

First of all, thanks for this library. 

I'm building a project with Parcel, and when trying to do any request, it fails with following error:
```
httpClient.ts:73 Uncaught (in promise) TypeError: Failed to execute 'fetch' on 'Window': Illegal invocation
```
The url and config are correct. If a try with another client, for example axios, it works perfectly, so it's a problem related to the library. Maybe some config problem with parcel?

I'll provide code if you need it, just tell me :)

**Comment by slavovojacek** [comment]
Hi, thanks for reaching out.

The problem you are facing stems from the fact that this library is only compatible with the Node.js platform/runtime, _not_ the browser.

In the browser, you'd have to use `isomorphic-fetch` I believe.
